{% set version = "1.2.1" %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: pytorch_spline_conv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/torch_spline_conv/torch_spline_conv-{{ version }}.tar.gz
  sha256: 364f658e0ecb4c5263a728c2961553e022fc44c11a633d5a1bf986cf169ab438

build:
  number: 6
  # as of pytorch 1.13, conda-forge only builds for CUDA 11.2+, see
  # https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3491
  skip: true  # [win or cuda_compiler_version in ("None", "10.2", "11.0", "11.1")]
  string: cpu_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  script:
    - export FORCE_CUDA="1"    # [linux64 and cuda_compiler_version != 'None']
    - export CC="$GCC"         # [linux64 and cuda_compiler_version != 'None']
    - export NVCC_FLAGS="--compiler-bindir=${CC}"    # [linux64 and cuda_compiler_version != 'None']
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
  host:
    - python
    - pytorch
    - pytorch =*={{ torch_proc_type }}*
    - setuptools
    - pytest-runner
    - pip
  run:
    - python
  run_constrained:
    # additional run constraint to the one from the (version-only) run_export;
    # constraining the CPU builds to CPU pytorch isn't 100% necessary, but cleaner
    - pytorch =*={{ torch_proc_type }}*

test:
  imports:
    - torch_spline_conv

about:
  home: https://github.com/rusty1s/pytorch_spline_conv
  summary: Implementation of the Spline-Based Convolution Operator of SplineCNN in PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - h-vetinari
    - rluria14
    - oblute
    - ndmaxar
