{% set name = "torch_spline_conv" %}
{% set version = "1.2.0" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7a1788004f6c6143d47040f2dd7d8a579a0c69a0cb0b5d7537416bf37c082a5

build:
  number: 5
  skip: true  # [win or cuda_compiler_version == 'None' or cuda_compiler_version == '10.2']
  script:
    - export FORCE_CUDA="1"    # [linux64 and cuda_compiler_version != 'None']
    - export CC="$GCC"   # [linux64 and cuda_compiler_version != 'None']
    - export NVCC_FLAGS="--compiler-bindir=${CC}"    # [linux64 and cuda_compiler_version != 'None']
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
  host:
    - python
    - pytorch
    - setuptools
    - pytest-runner
    - pip
  run:
    - python
    - pytorch
    - pytest
    - pytest-cov

test:
  imports:
    - torch_spline_conv
    
about:
  home: https://github.com/rusty1s/torch-spline-conv
  summary: Implementation of the Spline-Based Convolution Operator of SplineCNN in PyTorch
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/torch-spline-conv

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
